name: mikack
description: Dart binding for Mikack
# version: 1.0.0
homepage: https://github.com/Hentioe/mikack-dart

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  ffi: any

dev_dependencies:
  test: any
  grinder: any
